### PR TITLE
Update Index.cshtml

### PR DESCRIPTION
**Pull request by jkshapiro**
Added a less meme-worthy but simply excellent story to the Classic Articles section. As Acacio says in the comments, "We can close DWTF: after this one, all the rest will paleas watered down beer."

### CODE REVIEW

**Comment by apapadimoulis** [comment]
Good choice, but I think the long title will overflow; did you try it w/ browser tools to see if it looks weird?

**Comment by patrickwroach** [comment]
It should wrap appropriately

**Comment by BenLubar** [comment]
image

**Comment by patrickwroach** [comment]
Ah in the list, sorry I thought you meant the title area

**Pull request merged**
